# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    message_repository:
        class: AppBundle\Repository\MessageRepository
        arguments:
            - "@event_storage"

    event_storage:
        class: AppBundle\Repository\EventStorage
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\EventData